     1|name: kalimaya
     2|description: Kalimaya internal office app
     3|publish_to: none
     4|version: 0.1.0
     5|environment:
     6|  sdk: ">=3.0.0 <4.0.0"
     7|  flutter: ">=3.10.0"
     8|
     9|dependencies:
    10|  flutter:
    11|    sdk: flutter
    12|  flutter_localizations:
    13|    sdk: flutter
    14|  intl: ^0.19.0
    15|  http: ^1.2.0
    16|  shared_preferences: ^2.3.0
    17|  provider: ^6.1.2
    18|  google_fonts: ^6.2.1
    19|  cupertino_icons: ^1.0.8
    20|
    21|flutter:
    22|  uses-material-design: true
    23|